Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information
Monitoring:
  Settings:
    ShowUI: 'True'
    UseGlobalServiceName: 'Test'
  HealthChecks:
  - Name: Test
    ServiceType: Http
    EndpointOrHost: https://www.testendpoint.com/
    Port: 443
    HealthCheckConditions:
      HttpBehaviour:
        HttpExpectedResponseTimeMs: 300
        HttpExpectedCode: 200
        HttpVerb: Get
      ServiceReach: true
      ServiceConnectionEstablished: true
    PublishChecks: true
    Alert: true
    AlertBehaviour:
    - TransportMethod: Email
      TransportName: StandardEmailTransport
      AlertOnce: true
      AlertOnServiceRecovered: true
      StartAlertingOn: ''
      StopAlertingOn: ''
      AlertEvery: '00:00:05'
      AlertOn: ''
  - Name: Rmqtest
    ServiceType: Rmq
    EndpointOrHost: "amqp://user:test@localhost:5672/"
    PublishChecks: true
    Alert: true
    AlertBehaviour:
    - TransportMethod: Email
      TransportName: StandardEmailTransport
      AlertOnce: true
      AlertOnServiceRecovered: true
      StartAlertingOn: ''
      StopAlertingOn: ''
      AlertEvery: '00:00:05'
      AlertOn: ''
  - Name: ElasticTest
    ServiceType: ElasticSearch
    EndpointOrHost: http://test:9200/
    PublishChecks: true
    Alert: true
    AlertBehaviour:
    - TransportMethod: Email
      TransportName: StandardEmailTransport
      AlertOnce: true
      AlertOnServiceRecovered: true
      StartAlertingOn: ''
      StopAlertingOn: ''
      AlertEvery: '00:00:05'
      AlertOn: ''
  - Name: TurriCustom
    ServiceType: Custom
    FullClassName: Simple.Service.Monitoring.HealthCheck
    PublishChecks: true    
    Alert: true
    AlertBehaviour:
    - TransportMethod: Email
      TransportName: StandardEmailTransport
      AlertOnce: true
      AlertOnServiceRecovered: true
      StartAlertingOn: ''
      StopAlertingOn: ''
      AlertEvery: '00:00:05'
      AlertOn: ''
  CustomNotificationTransportSettings:
  EmailTransportSettings:
  - Name: StandardEmailTransport
    From: turrican@habitatsoft.com
    To: turrican@hotmail.com
    SmtpHost: turbomail.habitatsoft.com
    SmtpPort: 25
    Authentication: false
    Username: ''
    Password: ''
    Template: Plain
  InfluxDBTransportSettings:
  - Name: InfluxTransport1
    Host: 
    Database: health_checks
  TelegramTransportSettings:
  - Name: testchat
    BotName: '@testbot'
    BotApiToken: token
    ChatId: '-chatid'
  SlackTransportSettings:
  - Name: SlackTransport1
    Token: 
    Channel: 
    Username: "Health Checks"